name: build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - uses: docker://gcc:9
    - name: Build
      run: |
        ls
        pwd
        ./build.sh clean
        ./build.sh debug
        ./build.sh modules
