name: Library(libddos2@Ubuntu x86_64)

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Build
      uses: ./.github/workflows/library/

