name: Test(Ubuntu x86_64)

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Test
      uses: ./.github/workflows/test/

